/*
Based on https://stackoverflow.com/questions/44479282/preprocessor-concatenate-string-to-each-argument-in-va-args/44479664

Constructs a list of strings

CZMUT_BUILD_STRING_LIST(char, int, double)
will output
   "char","int","double"

CZMUT_BUILD_STRING_LIST_P(char, int, double)
will output
    F("char"),F("int"),F("double")
 
*/

#define CZMUT_EVAL(...) __VA_ARGS__
#define CZMUT_VARCOUNT(...) \
   CZMUT_EVAL(CZMUT_VARCOUNT_I(__VA_ARGS__,9,8,7,6,5,4,3,2,1,))
#define CZMUT_VARCOUNT_I(_,_9,_8,_7,_6,_5,_4,_3,_2,X_,...) X_
#define CZMUT_GLUE(X,Y) CZMUT_GLUE_I(X,Y)
#define CZMUT_GLUE_I(X,Y) X##Y
#define CZMUT_FIRST(...) CZMUT_EVAL(CZMUT_FIRST_I(__VA_ARGS__,))
#define CZMUT_FIRST_I(X,...) X
#define CZMUT_TUPLE_TAIL(...) CZMUT_EVAL(CZMUT_TUPLE_TAIL_I(__VA_ARGS__))
#define CZMUT_TUPLE_TAIL_I(X,...) (__VA_ARGS__)

#define CZMUT_TRANSFORM(NAME_, ARGS_) (CZMUT_GLUE(CZMUT_TRANSFORM_,CZMUT_VARCOUNT ARGS_)(NAME_, ARGS_))
#define CZMUT_TRANSFORM_1(NAME_, ARGS_) NAME_  ARGS_
#define CZMUT_TRANSFORM_2(NAME_, ARGS_) NAME_(CZMUT_FIRST ARGS_),CZMUT_TRANSFORM_1(NAME_,CZMUT_TUPLE_TAIL ARGS_)
#define CZMUT_TRANSFORM_3(NAME_, ARGS_) NAME_(CZMUT_FIRST ARGS_),CZMUT_TRANSFORM_2(NAME_,CZMUT_TUPLE_TAIL ARGS_)
#define CZMUT_TRANSFORM_4(NAME_, ARGS_) NAME_(CZMUT_FIRST ARGS_),CZMUT_TRANSFORM_3(NAME_,CZMUT_TUPLE_TAIL ARGS_)
#define CZMUT_TRANSFORM_5(NAME_, ARGS_) NAME_(CZMUT_FIRST ARGS_),CZMUT_TRANSFORM_4(NAME_,CZMUT_TUPLE_TAIL ARGS_)
#define CZMUT_TRANSFORM_6(NAME_, ARGS_) NAME_(CZMUT_FIRST ARGS_),CZMUT_TRANSFORM_5(NAME_,CZMUT_TUPLE_TAIL ARGS_)
#define CZMUT_TRANSFORM_7(NAME_, ARGS_) NAME_(CZMUT_FIRST ARGS_),CZMUT_TRANSFORM_6(NAME_,CZMUT_TUPLE_TAIL ARGS_)
#define CZMUT_TRANSFORM_8(NAME_, ARGS_) NAME_(CZMUT_FIRST ARGS_),CZMUT_TRANSFORM_7(NAME_,CZMUT_TUPLE_TAIL ARGS_)
#define CZMUT_TRANSFORM_9(NAME_, ARGS_) NAME_(CZMUT_FIRST ARGS_),CZMUT_TRANSFORM_8(NAME_,CZMUT_TUPLE_TAIL ARGS_)

#define CZMUT_MAKE_INITIALIZER(...)  __VA_ARGS__

#define CZMUT_Z_ARG(X) CZMUT_Z_ARG_(X)
#define CZMUT_Z_ARG_P(X) CZMUT_Z_ARG_P_(X)

#define CZMUT_BUILD_STRING_LIST(...) \
   CZMUT_EVAL(CZMUT_MAKE_INITIALIZER CZMUT_TRANSFORM(CZMUT_Z_ARG, (__VA_ARGS__)))

#define CZMUT_BUILD_STRING_LIST_P(...) \
   CZMUT_EVAL(CZMUT_MAKE_INITIALIZER CZMUT_TRANSFORM(CZMUT_Z_ARG_P, (__VA_ARGS__)))

#define CZMUT_Z_ARG_(X) #X
#define CZMUT_Z_ARG_P_(X) F(#X)
